dist: bionic
language: python
cache:
  - apt
  - pip
  - git
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.6
    env:
      - TOXENV=py36
  - python: 3.6
    env: TOXENV=style
  - python: 3.7
    env:
      - TOXENV=py37

install:
    - sudo apt-get install freeglut3-dev
    - git clone https://github.com/Dallinger/bams.git
    - pip install -r bams/requirements.txt
    - python bams/setup.py install
    - pip install -r requirements.txt
script:
    - pytest/tests