dist: bionic
language: python
cache:
  - apt
  - pip
  - git
matrix:
  include:
  - python: 3.6

install:
    - sudo apt-get install freeglut3-dev
    - git clone https://github.com/Dallinger/bams.git
    - cd bams
    - pip install -r requirements.txt
    - python setup.py install
    - cd ..
    - pip install -r requirements.txt
script:
    -  python -m pytest
